### ISSUE TITLE
Update BfR logo

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-server#109]
As a user I would like to see the current BfR logo. The current logo is outdated since October 2021.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTV1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8ffc9336b5debd246f6f115eb3d3c7d7b0d9ecc4/grafik.png)

Needs to be updated in graph/map, saved images thereof, ROA view and printed PDF thereof

Sent by AF on 10.11.2023 at 09:36.

**Comment by ruegenbfr** [comment]
This is a client ticket. Ticket was recreated in client repo (see SiLeBAT/fcl-client#747).
