### ISSUE TITLE
Consent status/date/time for GDPR in database

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-server#18]
Consent status and date + time of consent for GDPR needs to be written into the database. Date of publication of the latest GDPR needs to be written into the database (or check for the date on the bottom of the GDPR documents) to track if the user consented to the latest version of the GDPR

Which date is relevant for consent: registration date is saved and consent status is set to yes/true and as soon as the user confirmed the registration the date will be replaced by the date of confirmation via email

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by birgitlewicki** [comment]
When a user registers the following 2 fields are added to the user record in the db:

- dataProtectionDate: time and date of registration request
- dataProtectionAgreed: set to true, the user can only register if he agrees to the Privacy Policy
