### ISSUE TITLE
Confirmation email for newsletter consent

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-server#21]
As product-owner I would like to have a double opt-in for the newsletter subscription. The user should get an email with a confirmation button/link, similar to the procedure for the registration. Also, the reaction of the frontend to the confirmation via clicking the link in the email must be added (Api).

Email text:

Dear "first name" "name",

You have registered for the FCL newsletter. Use the link below to activate your subscription. This activation link is only valid for the next 24 hours.  

Activate your account  

If you’re having trouble with the link above, copy and paste the URL below into your web browser.  
"link"
  
You can unsubscribe from our newsletters at any time. Please write an e-mail to foodrisklabs@bfr.bund.de to unsubscribe. You will need the e-mail address that you gave when you registered.

The FCL Team 

For security, this request was received from a device using "browser/technical information". If you did not register for the FCL newsletter, please ignore this email or contact support if you have questions.

**Comment by afalenski** [comment]
Confirmation email was received, text is good, button worked. Done.
