### ISSUE TITLE
Activation of hamburger menu hides stations on the right

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-server#4]
As a FCL Web user I still want to see the same number of stations after activating the hamburger menu as I could before doing so.<br>
*To reproduce the bug:* Load example data, apply grid layout, activate the hamburger menu -> the stations on the right nearly completely dissapear. <br>
*Idea for quick fix:* Automatically zoom out a few percent (not as much as you do when clicking the minus button on the zoom controls).

**Comment by bfrgottscma** [comment]
Instead of changing the zoom, add a scroll bar

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/fcl-client #177](https://github.com/SiLeBAT/fcl-client/issues/177) via [**ZenHub**](https://www.zenhub.com/)
