### ISSUE TITLE
Remove whitespaces from jenkins build projects

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-server#74]
Jenkins uses project names also for workspace folders without removing white spaces. This can cause issues. E.g. the node-pre-gyp compile tool is unable to handle folder names with whitespaces and so fails.

E.g. as an example for Mibi Portal rename "mibi-portal nightly v1" to "mibi-portal_nightly_v1"

Note: In this ticket all our 43er projects should be renamed to address over-ticketing (Done for Mibi Portal)

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-server/74?planning-poker) with ZenHub @afalenski @GerberI @MicheleK17 @ruegenbfr

**Comment by ruegenbfr** [comment]
Done! 

7 pipelines renamed.
4 pipelines manually reconfigured.
