### ISSUE TITLE
Use new Jenkins pipeline and remove old pipeline

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-server#75]

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-server/75?planning-poker) with ZenHub @afalenski @GerberI @MicheleK17 @ruegenbfr

**Comment by ruegenbfr** [comment]
Unused pipelines removed.

Some pipelines I cannot remove (this option is not provided at least for me in jenkins).

@dptolle Please remove pipelines named **fcl\*(deprecated\***
