### ISSUE TITLE
Update server libs

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-server#77]
@ruegenbfr Please specify

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-server/77?planning-poker) with ZenHub @afalenski @GerberI @MicheleK17 @ruegenbfr
