### ISSUE TITLE
Complete externalisation of node server

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-server#80]
Ticket #68 was not completed. User cannot login anymore. 
Reason: The server uses apiUrl as apiRoot, which causes are 404 response.

ToDo:
- fix config files: 
  - Introduce new parameters **clientUrl**, **apiRoot**
  - Remove parameter **apiUrl**
  - introduce host config, seperate host specific attributes from environment specific ones
-  fix pipelines:
  - copy host specific config
-  Adapt server code to new parameters

**Comment by afalenski** [comment]
Login is possible again.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Browsers:
- Google Chrome Version 96.0.4664.110 (Offizieller Build) (64-Bit)
- Firefox 91.7.0 (64-Bit)
