### ISSUE TITLE
Change activation confirmation email text

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-server#84]
As a new user of FCL web who has started to register I would like to get a link to the FCL web portal in the activation confirmation email and as a member of the FCL web portal team I would like to see the correct international BfR name. 
For all changes: Keep old formatting (align left for text, align center for copyright), same fonts, text sizes and bold type.

- Change text 1
OLD: "The fcl-Portal administrator has just now activated your account. You can login now to the portal." 
NEW: "The FCL web portal administrator has activated your account. Now, you can log in to the [FCL web portal](https://fcl-portal.bfr.berlin)"
- Change text 2
OLD: The fcl-Portal team
NEW: The FCL web portal team
- Change text 3
OLD: 
(c) 2018 fcl-Portal. All rights reserved. 
BfR - Bundesinstitut für Risikobewertung
Max-Dohrn-Str. 8-10
10589 Berlin
NEW: 
(c) 2018 FCL web portal. All rights reserved. 
BfR - German Federal Institute for Risk Assessment
Max-Dohrn-Str. 8-10
10589 Berlin

Screenshot from old activation confirmation email:
![image.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/36228d18-892c-48a0-a370-9b4c7f08f12c)

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-server/84?planning-poker) with ZenHub @afalenski @birgitlewicki @GerberI @ruegenbfr

**Comment by afalenski** [comment]
Texts are fine. However, the link "FCL web portal" in Text 1 does not work. In one email tool in browser there was a link to the same email and in another email tool in browser there was no link.

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Browsers:
- Google Chrome Version 96.0.4664.110 (Offizieller Build) (64-Bit)

**Comment by birgitlewicki** [comment]
Checking link in email template

**Comment by birgitlewicki** [comment]
The constant client_url was not yet known to the email template and has been added.

**Comment by afalenski** [comment]
Link in email directed to the FCL web portal dev.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Browsers:
- Firefox 91.7.0 ESR
