### ISSUE TITLE
 Refine user repo 

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-server#88]
See  [gitlab SC Ticket 84](https://gitlab.bfr.berlin/devs43/common/SecurityConcept/issues/84)

**Comment by afalenski** [comment]
I have clicket on Password recovery twice, I received one email. Password recovery was in one case successful
I have read the Gitlab ticket but I do not know what else to test for this ticket.

**Comment by bfrgottscma** [comment]
Checked login on prod and dev. Problem described in Gitlab ticket seems solved.
