### ISSUE TITLE
Translate subject text in register / password recovery emails

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-server#99]
As a user who does not know German I would like to be able to understand the email subject in the registration emails and in the password recovery emails.

These are all emails sent to users:

Registration:
Old subject: "Aktivieren Sie Ihr Konto für FCL web portal "
New subject: " Activate your FCL web portal account"

Old subject: "Ihre Registrierung für ein FCL web portal Konto"
New subject: "Your FCL web portal registration"

Admin activation
Old subject: "Admin Aktivierung Ihres FCL web portal Kontos"
New subject: "The FCL web portal administrator has activated your account"

Old subject: "Noch keine Admin Aktivierung Ihres FCL web portal Kontos"
New subject: "The FCL web portal administrator has not yet activated your account"

Password recovery
Old subject: "Setzen Sie Ihr FCL web portal-Konto Passwort zurück."
New subject: "Reset the password for your FCL web portal account"

Successful password recovery
Old subject: "Passwort für FCL web portal-Konto erfolgreich zurückgesetzt."
New subject: "The password for your FCL web portal account was reset"

**Comment by ruegenbfr** [comment]
There are additional german texts:
- "Noch keine Admin Aktivierung Ihres FCL web portal Kontos" (Sended On Login attempt, when the user is registered but was not yet activated by an admin)
- "Ihre Registrierung für ein FCL web portal Konto" (Sended On Registration attempt when the user is already registered)

**Comment by afalenski** [comment]
@ruegenbfr Translations added to ticket text.

**Comment by bfrgottscma** [comment]
Tested for registration and PW reset. All subject texts are in line with the specifications. Done.
